services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  springboot_app:
    # build: .
    # image: springboot_demo
    image: azzcrimson30/springboot_demo:latest
    container_name: my-java-dev
    ports:
      - "8082:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_DATABASE=Springboot_db

volumes:
  mongo_data: