spring.application.name=demo
server.port=8080
# Connection URI (localhost port 27017)
# spring.mongodb.host=host.docker.internal
# spring.mongodb.uri=mongodb://localhost:27017/showroom
spring.mongodb.host=${SPRING_DATA_MONGODB_HOST:localhost}

# Alternative breakdown structure (Choose either uri above OR these properties below)
# spring.data.mongodb.host=localhost
# spring.data.mongodb.port=27017
# spring.data.mongodb.database=showroom
