name: Java CI/CD to Docker Hub

on:
  push:
    branches: [ "main" ]

jobs:
  # JOB 1: Built on the GitHub Cloud
  build-and-deploy:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Grant Execute Permission to Maven Wrapper
      run: chmod +x mvnw

    - name: Build and Test with Maven
      env:
        SPRING_DATA_MONGODB_HOST: localhost
        SPRING_DATA_MONGODB_DATABASE: Springboot_test_db
      run: ./mvnw clean package

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          azzcrimson30/springboot_demo:latest
          azzcrimson30/springboot_demo:${{ github.sha }}

  # JOB 2: Triggered automatically on YOUR laptop
  deploy-local:
    needs: build-and-deploy
    runs-on: self-hosted
    steps:
    - name: Pull and Restart Docker
      shell: powershell
      run: |
        cd C:\Users\TMOG-PC148\Documents\projects\Docker\springboot_demo
        docker compose pull springboot_app
        docker compose up -d --force-recreate springboot_app